### PR TITLE
paritygame as object + former paritygame type as arrayparitygame

### PR DESCRIPTION
**Pull request by bizzlshizzl**
This is an object-oriented implementation of the paritygame module. 

Therefore I created a **virtual paritygame class** (in paritygame.ml), which can (and must) be inherited to create an instantiable paritygame class.  Furthermore, I refactored the former array based type to this object-oriented approach. The corresponding module is called **arrayparitygame.ml**.

In addition, I adapted the whole project and tested it. BUT I did not include my edited _oasis file because I am not sure if my changes to it were the best way considering the whole project. This means, this project is not buildable as is, but some minor adaptions in the build process will fix it.

I included two files in this message: The first one is a small comparison of the runtime between the paritygame type implementation and this object-oriented implementation. The second one is a short overview of some methods that are currently class methods but are only used in one or two places. So it would make sense to exclude them from the actual paritygame object.

Cheers

[PDF: runtime comparison](https://github.com/tcsprojects/pgsolver/files/1272988/runtime_comparison_paritygame.pdf)
[PDF: methods to be excluded](https://github.com/tcsprojects/pgsolver/files/1273023/methods_to_be_removed.pdf)

### CODE REVIEW

**Comment by oliverfriedmann** [comment]
Thank you for the pull request! Could you post your modified _oasis file here in the comments?

**Comment by bizzlshizzl** [comment]
Sure.
I only edited two things:

- I needed to add a version to the META Plugin (don't know why it complained here but not in the original one). I chose 0.4.
- I added Arrayparitygame in de Modules section.

After that I ran _oasis setup -setup-update dynamic_ in the pgsolver folder and the standard build process worked as before (ocaml setup.ml -configure, ...).

[modified _oasis as txt](https://github.com/tcsprojects/pgsolver/files/1280189/_oasis.txt)

**Comment by oliverfriedmann** [comment]
Works well. Can you add your modified _oasis to the commit and create the pull request for the develop branch instead of the master branch? Will pull it in then.

**Comment by bizzlshizzl** [comment]
Done. I noticed that the _oasis setup -setup-update dynamic_  command changed the setup.ml strongly. I added it anyway because this way the project is out of the box buildable.

**Comment by oliverfriedmann** [comment]
thank you!

**Pull request merged**
