### PR TITLE
External solver

### PR DESCRIPTION
**Pull request by Rupsbant**
I currently have an external parity game solver and I would like to integrate it in your framework.

I don't know if you use an auto-formatter. Atom wanted to change a lot of tabs/spaces and empty lines. I tried to remove the majority from the pull-request.

Also in `parity_game.ml` line 367 I changed the header from the number nodes to the maximum node number, in accordance to the behaviour of `game_to_string` line 361. I don't know if this is correct.

### CODE REVIEW

**Comment by Rupsbant** [comment]
I have cleaned the commits a bit (more), I forgot to remove two redundant commits.

I haven't regenerated the `setup.ml` command because I probably use a newer version of oasis which removes about 11000 lines.

**Comment by oliverfriedmann** [comment]
Hi there,

Thank you for your PR. I'm getting this error when compiling:

`File "src/solvers/externalsolver.ml", line 13, characters 41-47:
Error: This expression has type bytes but an expression was expected of type
         string
`

Any idea?

Thanks,
Oliver

**Comment by trolando** [comment]
Ah, interesting this, one could use Oink as the external solver then! :-)

**Comment by Rupsbant** [comment]
@oliverfriedmann 
See https://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html

> This is done by making the types string and bytes (see module Bytes) interchangeable so that functions expecting byte sequences can also accept strings as arguments and modify them.

I added a commit that should solve this.

**Pull request merged**
